apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: flying-hamster-nodejs 
  janus-idp.io/tekton: flying-hamster-nodejs
  backstage.io/kubernetes-id: flying-hamster-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: flying-hamster-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  