apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: flying-hamster-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flying-hamster-nodejs 
  name: flying-hamster-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: flying-hamster-nodejs 
